version: '3.7'

# reading connection values from .env file using volumes field instead of  environment
services:
  app:
    image: service-app
    container_name: service-http-avito-test
    build: 
      context: ../
      dockerfile: build/package/Dockerfile
    ports:
      - "9090:9090"
    volumes: 
      - "../.env:/.env"  
    depends_on:
      - postgres  


  postgres:
    image: postgres:12.3
    container_name: postgres
    init: true
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"  
    volumes:
      - "../scripts/postgres:/docker-entrypoint-initdb.d/"          
