version: '3.7'

services:
  app:
    image: app
    container_name: server
    build: 
      context: ../
      dockerfile: build/package/Dockerfile
    env_file:
      - ../.env
    environment:
      PGHOST: "postgres"
      PGPORT: "5432"  
    ports:
      - "9090:9090"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.3
    container_name: postgres
    init: true
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "postgres"
    ports:
      - "5432:5432"  
    volumes:
      - "../scripts/postgres:/docker-entrypoint-initdb.d/"          
