// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package mock_server is a generated GoMock package.
package server

import (
	context "context"
	storage "http-avito-test/internal/storage"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	decimal "github.com/shopspring/decimal"
)

// MockStorager is a mock of Storager interface.
type MockStorager struct {
	ctrl     *gomock.Controller
	recorder *MockStoragerMockRecorder
}

// MockStoragerMockRecorder is the mock recorder for MockStorager.
type MockStoragerMockRecorder struct {
	mock *MockStorager
}

// NewMockStorager creates a new mock instance.
func NewMockStorager(ctrl *gomock.Controller) *MockStorager {
	mock := &MockStorager{ctrl: ctrl}
	mock.recorder = &MockStoragerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorager) EXPECT() *MockStoragerMockRecorder {
	return m.recorder
}

// Deposit mocks base method.
func (m *MockStorager) Deposit(arg0 int64, arg1 decimal.Decimal, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Deposit", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Deposit indicates an expected call of Deposit.
func (mr *MockStoragerMockRecorder) Deposit(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Deposit", reflect.TypeOf((*MockStorager)(nil).Deposit), arg0, arg1, arg2)
}

// ReadClient mocks base method.
func (m *MockStorager) ReadClient(arg0 int64, arg1 context.Context) (storage.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadClient", arg0, arg1)
	ret0, _ := ret[0].(storage.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadClient indicates an expected call of ReadClient.
func (mr *MockStoragerMockRecorder) ReadClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadClient", reflect.TypeOf((*MockStorager)(nil).ReadClient), arg0, arg1)
}

// ReadUserHistoryList mocks base method.
func (m *MockStorager) ReadUserHistoryList(user_id int64, sort string, ctx context.Context) ([]storage.Transf, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadUserHistoryList", user_id, sort, ctx)
	ret0, _ := ret[0].([]storage.Transf)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadUserHistoryList indicates an expected call of ReadUserHistoryList.
func (mr *MockStoragerMockRecorder) ReadUserHistoryList(user_id, sort, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadUserHistoryList", reflect.TypeOf((*MockStorager)(nil).ReadUserHistoryList), user_id, sort, ctx)
}

// Transfer mocks base method.
func (m *MockStorager) Transfer(user_id1, user_id2 int64, amount decimal.Decimal, ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transfer", user_id1, user_id2, amount, ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Transfer indicates an expected call of Transfer.
func (mr *MockStoragerMockRecorder) Transfer(user_id1, user_id2, amount, ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transfer", reflect.TypeOf((*MockStorager)(nil).Transfer), user_id1, user_id2, amount, ctx)
}

// Withdrawal mocks base method.
func (m *MockStorager) Withdrawal(arg0 int64, arg1 decimal.Decimal, arg2 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Withdrawal", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Withdrawal indicates an expected call of Withdrawal.
func (mr *MockStoragerMockRecorder) Withdrawal(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Withdrawal", reflect.TypeOf((*MockStorager)(nil).Withdrawal), arg0, arg1, arg2)
}
