CREATE TABLE Bankacc (
    user_id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    balance bigint NOT NULL,
);
GO

INSERT INTO Bankacc (user_id, balance) VALUES
  (N'Jared',  N'Australia'),
  (N'Nikita', N'India'),
  (N'Tom',    N'Germany');
GO

SELECT * FROM Bankacc;
GO