CREATE TABLE bankacc (
    user_id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    balance bigint NOT NULL
);
GO

INSERT INTO bankacc (user_id, balance) 
			VALUES ($ID, $Bank) ON CONFLICT (user_id) 
			DO UPDATE SET balance = (SELECT balance + $Bank FROM bankacc WHERE user_id = $ID) 
			WHERE bankacc.user_id = $ID;
GO

SELECT * FROM bankacc;
GO