openapi: 3.0.0
info: 
  version: 1.0.0
  title: server API
  description: yaml file for description the response data

paths: 
  /api/{version}/readuser:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Read user
      operationId: ReadUser 

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadUserRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadUserResponse'

  /api/{version}/reservationoffunds:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:  
      summary: Reservation of funds
      operationId: ReservationOfFunds

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReservationOfFundsRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReservationOfFundsResponse'

  /api/{version}/monthlyreport:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:  
      summary: Monthly Report
      operationId: MonthlyReport

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MonthlyReportRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MonthlyReportResponse'

  /api/{version}/unreservationoffunds:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:  
      summary: Unreservation of funds
      operationId: UnreservationOfFunds

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UnreservationOfFundsRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnreservationOfFundsResponse'

  /api/{version}/revenuerecognition:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:  
      summary: Revenue Recognition
      operationId: RevenueRecognition

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevenueRecognitionRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevenueRecognitionResponse'  

  /api/{version}/readuserhistory:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Read user history
      operationId: ReadUserHistory 

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ReadUserHistoryRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReadUserHistoryResponse'
          
  /api/{version}/accountdeposit:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Account deposit
      operationId: AccountDeposit 

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountDepositRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountDepositResponse'

  /api/{version}/accountwithdrawal:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Account withdrawal
      operationId: AccountWithdrawal 

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountWithdrawalRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountWithdrawalResponse'

  /api/{version}/transfercommand:
    parameters:
      - $ref: '#/components/parameters/Version'

    post:
      summary: Transfer command
      operationId: TransferCommand 

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferCommandRequest'

      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferCommandResponse'

components:

  parameters:
    Version:
      name: version
      description: api version
      in: path 
      schema: 
        type: integer
        format: int64
      required: true

  schemas:

    RevenueRecognitionRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        service_id:
          type: integer
          format: int64
        order_id:
          type: integer
          format: int64
        sum:
          type: number
      required:
        - user_id
        - service_id
        - order_id
        - sum

    MonthlyReportRequest:
      type: object
      properties:
        year:
          type: integer
          format: int64
        month:
          type: integer
          format: int64
      required:
        - year
        - month  

    ReservationOfFundsRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        service_id:
          type: integer
          format: int64
        order_id:
          type: integer
          format: int64
        price:
          type: number
      required:
        - user_id
        - service_id
        - order_id
        - price   

    UnreservationOfFundsRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        service_id:
          type: integer
          format: int64
        order_id:
          type: integer
          format: int64
      required:
        - user_id
        - service_id
        - order_id

    ReadUserRequest:
      type: object
      properties:
        user_id:
          type: integer
          format: int64
        currency: 
          type: string
          nullable: true
      required:
        - user_id
        - currency

    ReadUserHistoryRequest:
      type: object
      properties:
        user_id: 
          type: integer
          format: int64
        order: 
          x-go-type: storage.OrdBy
          x-go-type-import: 
            name: OrdBy
            path: http-avito-test/internal/storage
        limit: 
          type: integer
          format: int64
        offset: 
          type: integer 
          format: int64
      required:	
        - user_id
        - order
        - limit
        - offset

    AccountDepositRequest:
      type: object
      properties:
        user_id: 
          type: integer
          format: int64
        amount: 
          type: number
      required: 
        - user_id
        - amount    

    AccountWithdrawalRequest:
      type: object
      properties:
        user_id: 
          type: integer
          format: int64
        amount: 
          type: number 
        description:
          type: string
          nullable: true
      required: 
        - user_id
        - amount
        - description	

    TransferCommandRequest:
      type: object
      properties:
        sender:
          type: integer
          format: int64
        recipient: 
          type: integer
          format: int64
        amount:
          type: number
        description:
          type: string
          nullable: true
      required:
        - sender
        - recipient
        - amount
        - description

    ReadUserResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: object
          properties:
            user_id:
              type: integer
              format: int64
            balance:
              x-go-type: decimal.Decimal
              x-go-type-import:
                name: decimal
                path: github.com/shopspring/decimal
          required:
            - user_id
            - balance       
      required: 
        - status
        - result   

    MonthlyReportResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: object
          properties:
            link:
              type: string
          required:
            - link
      required:
        - status
        - result            

    ReadUserHistoryResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: array
          items:
            x-go-type: storage.ReadUserHistoryResult
            x-go-type-import: 
              name: readuserhistoryresult
              path: http-avito-test/internal/storage
      required: 
        - status
        - result
            
    AccountDepositResponse:
      type: object
      properties:
        status:
          type: string
        result:
          type: object
          properties:
            message:
              type: string
          required:
            - message
      required:
        - status
        - result

    AccountWithdrawalResponse:
      $ref: '#/components/schemas/AccountDepositResponse'

    ReservationOfFundsResponse:
      $ref: '#/components/schemas/AccountDepositResponse'  

    UnreservationOfFundsResponse:
      $ref: '#/components/schemas/AccountDepositResponse'

    TransferCommandResponse:
      $ref: '#/components/schemas/AccountDepositResponse'

    RevenueRecognitionResponse:
      $ref: '#/components/schemas/AccountDepositResponse'  